### PR TITLE
abspath

### PR DESCRIPTION
**Pull request by ext**
Fixes my issue with symlinks.

### CODE REVIEW

**Comment by xtaran** [comment]
This broke Planet Venus on Debian Lenny. Had to revert it locally. Otherwise it didn't find htmltmplc (installed from the python-htmltmplc package) anymore.

**Comment by ext** [comment]
That sounds very odd, could you open an issue with the errors you receive and briefly explain your setup? Do you use a symlink? Does the file have the proper extension?

**Comment by xtaran** [comment]
This is the error I get at the end of a `planet.py $planet/config.ini` run:

```
INFO:planet.runner:Loading cached data
Traceback (most recent call last):
  File "./planet.py", line 89, in <module>
    splice.apply(doc.toxml('utf-8'))
  File "/home/planet/venus/planet/splice.py", line 142, in apply
    output_file = shell.run(template_file, doc)
  File "/home/planet/venus/planet/shell/__init__.py", line 66, in run
    module.run(template_resolved, doc, output_file, options)
  File "/home/planet/venus/planet/shell/tmpl.py", line 253, in run
    template = manager.prepare(script)
  File "/home/planet/venus/planet/vendor/htmltmpl.py", line 172, in prepare
    precompiled = self.load_precompiled(file)
  File "/home/planet/venus/planet/vendor/htmltmpl.py", line 267, in load_precompiled
    precompiled = cPickle.load(file)
ImportError: No module named htmltmpl
```

Here's the packages file list (docs and directories excluded):

```
-rw-r--r-- 1 root root  5722 2001-09-01 14:31 /usr/share/python-support/python-htmltmpl/easydocp.py
-rw-r--r-- 1 root root 13110 2001-09-06 01:03 /usr/share/python-support/python-htmltmpl/easydoc.py
-rw-r--r-- 1 root root 58746 2006-06-15 02:30 /usr/share/python-support/python-htmltmpl/htmltmpl.py
lrwxrwxrwx 1 root root    53 2009-07-21 14:07 /var/lib/python-support/python2.5/htmltmpl.py -> /usr/share/python-support/python-htmltmpl/htmltmpl.py
-rw-r--r-- 1 root root 44634 2009-07-21 14:07 /var/lib/python-support/python2.5/htmltmpl.pyc
```

Version of the package python-htmltmpl is 1.22-10.

Using git bisect I found out that this commit was the one which broke it. Worked fine before as well as after reverting it.

**Comment by ext** [comment]
I'm trying to reproduce this but so far I haven't succeeded, could you try removing your *.tmplc files?

**Comment by xtaran** [comment]
That fixed it, too. Thanks! I wasn't aware that there are library paths or similar stuff compiled into these files. Sorry for the noise.

**Pull request merged**
